permissions:
  users:
    - create
    - update
    - delete
    - view
    - view_all
    - view_active
    - view_inactive
    - view_suspended
    - activate
    - deactivate
    - grant_access
    - revoke_access
  roles:
    - update
    - view
    - view_all
    - toggle_permission
    - activate
    - deactivate
  request_logs:
    - view
    - view_all
  dashboards:
    - view
  warehouses:
    - create
    - update
    - delete
    - view
    - view_all
    - view_active
    - view_inactive
    - activate
    - deactivate
  products:
    - create
    - update
    - delete
    - view
    - view_all
    - view_active
    - view_inactive
    - activate
    - deactivate
  product_prices:
    - create
    - update
    - delete
    - view
  inventories:
    - create
    - update
    - delete
    - view
    - view_all
    - view_movements
    - view_logs
    - restock
  inventory_batches:
    - create
    - update
    - delete
    - view
    - view_all
    - view_logs
  purchase_orders:
    - create
    - update
    - delete
    - view
    - view_all
    - cancel
    - submit
    - approve
    - reject
    - close
    - hold
  purchase_order_items:
    - create
    - update
    - delete
    - view
    - view_all
    - cancel
    - deliver
  tax_rates:
    - create
    - update
    - delete
    - view
    - view_all
    - view_active
    - view_expired
    - view_future
  feedbacks:
    - create
    - update
    - view
    - view_all
    - view_read
    - view_unread
    - mark_as_read
  profiles:
    - update
    - view
  preferences:
    - update
    - view
  legal_identifiers:
    - create
    - update
    - delete
    - view
    - view_all
    - view_approved
    - view_unapproved
    - view_rejected
    - approve
    - reject
  product_categories:
    - create
    - update
    - delete
    - view
    - view_all
    - view_active
    - view_inactive
  units_n_conversions:
    - view
